### ISSUE TITLE
Sanitize possible undefined's in dag-jose-utils

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/ceramic#205]

**Comment by oed** [comment]
Maybe we leave this to the application?

**Comment by PaulLeCam** [comment]
@oed at what level do you think this should be handled please? IMO providing `schema: undefined` (or any other metadata field) when creating a TileDocument should be be handled properly by Ceramic or the underlying libraries.
I think the most convenient is having `dag-jose-utils` handle it so it's not something consumers need to worry about, no?
In any case I don't think this should ever be an application-level concern.

**Comment by ukstv** [comment]
@PaulLeCam @oed IMO, the way forward is not to sanitise anything.

Sanitation of a JSON _object_ requires either removal of a property with `undefined` value, or coercion to `null`. There is also a case of an _array_, where we can only coerce a value to `null` so not to mess with ordering of values.

There is a subtle semantic difference between `undefined` and `null`. Some people employ the difference in the code. When doing sanitation, we risk messing with the developers intent without her knowing about it. We basically create a leaky abstraction. In this (edge) case, we'll have to explain _both_ IPLD constraints and our approach.

If we do no sanitation, no abstraction is leaking. The only thing to do for us is to ensure that code of ours in js-ceramic behaves properly, and does not push `undefined` to IPFS. And, it is quite easily achievable: upgrade to latest js-ipfs, run our existing test suite. If there is something that pushes `undefined` we see it immediately.

**Comment by PaulLeCam** [comment]
I'm concerned this will lead to the same kind of issue we're seeing now with the strictness change once we have different client/server serialization for example.

I agree we can do this sanitation on top of the codec, but that doesn't change the problem of having to do it somewhere at the Ceramic level, right? If I create a tile with `{foo: undefined}` content, what happens?
My guess is that it's not a problem now because we use the HTTP client, which serializes to JSON and therefore discards `undefined`, but what if we start using a binary protocol for encoding and the Ceramic node has to deal with this `undefined` content, do we start breaking apps because they switch to this binary protocol rather than JSON?
At least we need to implement this serialization in the DID library to make sure `createJWS()` works because that was the issue in the first place when creating signed commits locally and then pushing them to Ceramic.

IMO the role of the codec is to provide the same guaranties as `JSON.stringify()` where valid JS gets transformed to valid JSON even if some values are removed or transformed in the process.

**Comment by stbrody** [comment]
> what if we start using a binary protocol for encoding and the Ceramic node has to deal with this undefined content

I assume that if we changed encoding protocols the new one would need to keep the same semantics as our current one.  I.E. the binary encoding protocol would need to strip out `undefined` fields, the same as our current JSON encoding does.

**Comment by stbrody** [comment]
JS having both `null` AND `undefined` is relatively rare for programming languages.  I imagine as we become more language agnostic we'll want to keep to some standard universal set of types we support, and I think `undefined` won't be one of them.

**Comment by ukstv** [comment]
I guess this is the most important question:

> If I create a tile with {foo: undefined} content, what happens?

There are two options where this can happen.
1. Genesis for deterministic Tile stream. Usual top-level properties are _required_ to be defined. You can put `undefined` as one of the tags though. In this case, this `undefined` value is coerced into `null` through JSON serialization. Guess, a good idea here is to call dag-cbor encoding inside Tile.deterministic before doing a request to avoid such coercion.
2. Signed commit (either genesis or an update). This goes through `did::createDagJWS`, which serialises payload as DAG-CBOR. If `undefined` appears, it throws an error. If using http-client, this goes before doing a network request. Note: transport layer, JSON serialization are not involved at all.

As for an error message, code like this:
```typescript
const payload = {
    foo: 'string',
    blah: undefined
}
await did.createDagJWS(payload)
```
results in `Error: `undefined` is not supported by the IPLD Data Model and cannot be encoded`.

One could argue, this is not the most friendly error message. It contains no information on what field is undefined. Maybe we should tell a consumer what field is not accepted. To do this, though, we'll have to parse every JSON object on our own, which leads to degraded performance right away with questionable benefit.

**Comment by stbrody** [comment]
> results in `Error: `undefined` is not supported by the IPLD Data Model and cannot be encoded`.
> 
> One could argue, this is not the most friendly error message. It contains no information on what field is undefined. Maybe we should tell a consumer what field is not accepted. To do this, though, we'll have to parse every JSON object on our own, which leads to degraded performance right away with questionable benefit.

got it, thanks for the info.  That seems like a reasonable error message to start with, and I agree we should avoid inspecting every field in the object if we can avoid it.
