### ISSUE TITLE
3ID Identity section links result in 404's

### ISSUE THREAD

**Issue by sydbarrett74** [ceramicnetwork/ceramic#31]
In the '3ID Identity' section of the overview, the '3IDs' and 'example' links land on a 404 page.

**Comment by sydbarrett74** [comment]
Updates?

**Comment by michaelsena** [comment]
Hey @sydbarrett74 apologies, this slipped through. That document is quite out of date at the moment. We have been busy updating other more practical aspects such as developer documentation at https://developers.ceramic.network.

We changed the way we represent 3IDs on Ceramic, from being their own doctype, to now just being a Tile with some specific setup. That's why they're now resulting in 404s -- because those pages are not since deleted.

Pinging @oed to ask what's the latest best place to get more information about our current 3ID implementation.

**Comment by sydbarrett74** [comment]
@michaelsena Thank you for the update. :D
