### ISSUE TITLE
Is there a public calendar with the Ceramic Network calls?

### ISSUE THREAD

**Issue by daviddias** [ceramicnetwork/ceramic#6]
Hi folks! I'm really enjoying to get to discover Ceramic! Watched through https://www.youtube.com/watch?v=AplPOcWdVik

Can you confirm when is the next Call for the technical discussion? I would love to join and share notes! Do you have a Community Calendar with all your calls?

We spent some time developing a lot of similar ideas in the past with a large bet on CRDT, Cryptographic ACLs and Verifiable Claims. In case you are curious, you can check (everything is open and MIT licensed):
- [Building dApps on PermaWeb using PeerBase, a tool kit for building DApps with Cryptographic ACLs and CRDTs](https://www.youtube.com/watch?v=6PQ3Q-Z691I)
- [PeerPad, a collaborative doc editor on top of PeerBase](https://peerpad.net)
- [Distributed Verifiable Claims with IPFS and Ethereum](https://www.youtube.com/watch?v=4oIvWldzT4o) (the sound recording on this one isn't perfect, apologies for that in advance)
- [Identity on the DWeb Research and RFC](https://github.com/peer-base/peer-star/pull/15/files)
- [Nomios, Identity Wallet](https://nomios.io)

//cc @pgte @satazor @joaosantos15 @jimpick @dirkmc who I'm sure will enjoy learning about Ceramic and discussing ideas as well

Keep up the great work! 🌟🌟🌟🌟🌟🌟

PS: I'm curious on the name, is it Ceramic because you are building the Porcelain on top of all the other protocols or because you use Tiles as a concept?

**Comment by oed** [comment]
Hey @daviddias! Glad you're enjoying digging in :)

We will host a technical webinar which will go though the specs and a demo of the ceramic-cli. It will take place April 9, 2020, at 17 CET. 
Calendar invite here: https://calendar.google.com/event?action=TEMPLATE&tmeid=dnVkcmYyaDJhOTV0dDNlYmM0MGNqaG4xMjQgb2VkQDNib3guaW8&tmsrc=oed%403box.io
A community calendar sounds like a good idea cc @michaelsena 

Thanks for these links, I think we're already aware of most of it and I think Ceramic moves us closer to many of these goals. About CRDTs and collaborative apps I think Ceramic acts as a connective tissue that allows users to find each other and do fast paced collaboration in database systems such as Textile and OrbitDB. Ceramic would in these allow the data and schemas to be discoverable. This will make it easier for apps to build apps that utilize the data of other apps since they can explore the schemas and data collections availible on the network. We hope to be publishing more information about this and user-centric routing soon!

> the Porcelain on top of all the other protocols

Haha, haven't heard that one before. That's neat :) 
Ceramic is actually a really strong material that is used in jet engines etc, it can also be used to create fibers and fabric that is very heat resistant. Ceramic as a material is quite interesting!

**Comment by daviddias** [comment]
Thanks @oed! The calendar invite is not working for me, could you check please?

<img width="290" alt="image" src="https://user-images.githubusercontent.com/1211152/78353887-c34d5b80-75a2-11ea-87d2-a5de162e3a81.png">

**Comment by oed** [comment]
@daviddias I updated the link, can you try again?

**Comment by daviddias** [comment]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/1211152/78365183-9f941080-75b6-11ea-9ae0-640c8148bf19.png">

Got it 👌🏽 ! Looking forward for the session! :)

**Comment by michaelsena** [comment]
Hey @daviddias (and @pgte, @satazor, @joaosantos15, @jimpick, @dirkmc), following back up here! We just created a public calendar for Ceramic where we will add all events. Hope to see you all at some upcoming calls. :)

You can add the Ceramic calendar to your cal via this link: https://calendar.google.com/calendar/b/3?cid=Y2VyYW1pYy5uZXR3b3JrX3JsNzFrcXZtNzE4ZGY4aWk2cDZzanNmbDdjQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20
